---
- name: Install  Maven
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: Install Apache Maven
      shell: |
        wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz -O /tmp/maven.tar.gz
        tar -xvf /tmp/maven.tar.gz -C /opt
        ln -s /opt/apache-maven-3.8.6 /opt/maven
        echo 'export PATH=$PATH:/opt/maven/bin' >> /etc/profile.d/maven.sh
        echo 'export MAVEN_HOME=/opt/maven' >> /etc/profile.d/maven.sh

    - name: Make Maven executable
      file:
        path: /home/ansible/
        mode: '0755'
